"""hanzo is a build backend for modern Python based on ninja."""

import os
import subprocess
from datetime import datetime
from pathlib import Path

from hanzo.ninja import NinjaWriter, get_ninja_executable
from hanzo.rules import Rule
from hanzo.settings import (
    BuildConfig,
    load_extensions,
    parse_hanzo_settings,
    parse_project_metadata,
)
from hanzo.targets import CCExtensionTarget
from hanzo.utils import calculate_wheel_tag, to_snakecase
from hanzo.wheelfile import WheelWriter

__version__ = "0.1.0"

BUILD_DIRNAME = "build"
WHEEL_FILENAME = "{name}-{version}-{tag}.whl"


# PEP 517 hooks


def build_wheel(
    wheel_directory: str | os.PathLike[str],
    config_settings: dict[str, str] | None = None,
    metadata_directory: str | os.PathLike[str] | None = None,
) -> str:
    metadata = parse_project_metadata()
    settings = parse_hanzo_settings()
    config = BuildConfig.from_settings(config_settings or {})
    # TODO: Maybe give an option to disable builtin features
    config.add_builtin_features(settings)

    wheel_directory = Path(wheel_directory)
    (build_dir := Path.cwd() / BUILD_DIRNAME).mkdir(exist_ok=True)

    ext_modules = load_extensions(config)
    root_is_purelib = not ext_modules

    tag = calculate_wheel_tag(settings, config, root_is_purelib)

    project_name = to_snakecase(metadata.name)
    wheel_file = wheel_directory / WHEEL_FILENAME.format(
        name=project_name,
        version=metadata.version,
        tag=tag,
    )

    if not root_is_purelib:
        with open(build_dir / "build.ninja", "w") as ninjafile:
            ninja = NinjaWriter(ninjafile, width=1000)
            ninja.comment(f"Generated by hanzo v{__version__}")

            ruleset: set[Rule] = set()
            all: list[str] = []
            for ext in ext_modules.values():
                # TODO: Remove with rmtree() if clean build specified
                # TODO: Collect ruleset from all extensions before writing
                # to avoid duplicates.
                for rule in ext.rules.values():
                    if rule not in ruleset:
                        rule = rule.interpolate(config.cc)
                        ruleset.add(rule)
                        ninja.rule(
                            rule.name,
                            rule.command,
                            description=rule.description,
                            depfile=rule.depfile,
                            deps=rule.deps,
                        )
                        ninja.newline()

                for out in ext.build_outputs():
                    ninja.build(**out)
                    ninja.newline()

                # TODO: Find a more clever way to mark a target as default, and/or just
                # make all `cc-extension`s default.
                if isinstance(ext, CCExtensionTarget):
                    all.append(ext.libname)

            ninja.build("all", "phony", all)
            ninja.newline()
            ninja.default("all")

        ninja_exe = get_ninja_executable()
        subprocess.check_call([ninja_exe, "-C", str(build_dir)], shell=False)  # noqa: S603

    with WheelWriter(
        wheel_file, generator=f"hanzo {__version__}", root_is_purelib=root_is_purelib
    ) as wheel:
        project_path = Path(project_name)
        # step 1: create dist-info dir, write metadata into it.
        # TODO: Move into prepare_metadata
        wheel.write_metadata(metadata)

        # TODO: Create a more comprehensive wheel inclusion list with .gitignore and others.
        for dirpath, dirnames, files in os.walk("src"):
            for f in files:
                wheel.write_file(project_path / f, Path(dirpath) / f, timestamp=datetime.now())

        for file in build_dir.iterdir():
            # TODO: Refine this based on the expected kinds of build artifacts,
            # optimally from settings.
            if file.suffix == ".so":
                wheel.write_file(
                    project_path / file.name, build_dir / file, timestamp=datetime.now()
                )

    return wheel_file.name


def build_sdist(
    sdist_directory: str | os.PathLike[str],
    config_settings: dict[str, str] | None = None,
) -> str: ...


def get_requires_for_build_wheel(
    config_settings: dict[str, str] | None = None,
) -> list[str]:
    return []


def get_requires_for_build_sdist(
    config_settings: dict[str, str] | None = None,
) -> list[str]:
    return []


def prepare_metadata_for_build_wheel(
    metadata_directory: str | os.PathLike[str],
    config_settings: dict[str, str] | None = None,
) -> None:
    """Creates a .dist-info directory for the project, and writes metadata files into it
    (METADATA, RECORD, WHEEL).

    Currently, all metadata is handled in build_wheel(), so this function does nothing.

    TODO: Implement metadata writing in this hook, and just call it within build_wheel().
    """
    pass


# PEP 660 editable hooks


def build_editable(
    wheel_directory: str | os.PathLike[str],
    config_settings: dict[str, str] | None = None,
    metadata_directory: str | os.PathLike[str] | None = None,
) -> str:
    metadata = parse_project_metadata()
    settings = parse_hanzo_settings()
    config = BuildConfig.from_settings(config_settings or {})
    # TODO: Maybe give an option to disable builtin features
    config.add_builtin_features(settings)

    wheel_directory = Path(wheel_directory)
    (build_dir := Path.cwd() / BUILD_DIRNAME).mkdir(exist_ok=True)

    ext_modules = load_extensions(config)
    root_is_purelib = not ext_modules

    tag = calculate_wheel_tag(settings, config, root_is_purelib)

    project_name = to_snakecase(metadata.name)
    wheel_file = wheel_directory / WHEEL_FILENAME.format(
        name=project_name,
        version=metadata.version,
        tag=tag,
    )

    if not root_is_purelib:
        with open(build_dir / "build.ninja", "w") as ninjafile:
            ninja = NinjaWriter(ninjafile, width=1000)
            ninja.comment(f"Generated by hanzo v{__version__}")

            ruleset: set[Rule] = set()
            all: list[str] = []
            for ext in ext_modules.values():
                # TODO: Remove with rmtree() if clean build specified
                # TODO: Collect ruleset from all extensions before writing
                # to avoid duplicates.
                for rule in ext.rules.values():
                    if rule not in ruleset:
                        rule = rule.interpolate(config.cc)
                        ruleset.add(rule)
                        ninja.rule(
                            rule.name,
                            rule.command,
                            description=rule.description,
                            deps=rule.deps,
                            depfile=rule.depfile,
                        )

                for out in ext.build_outputs():
                    ninja.build(**out)
                    ninja.newline()

                # TODO: Find a more clever way to mark a target as default, and/or just
                # make all `cc-extension`s default.
                if isinstance(ext, CCExtensionTarget):
                    all.append(ext.libname)

            ninja.build("all", "phony", all)
            ninja.newline()
            ninja.default("all")

        ninja_exe = get_ninja_executable()
        subprocess.check_call([ninja_exe, "-C", str(build_dir)], shell=False)  # noqa: S603

    with WheelWriter(
        wheel_file, generator=f"hanzo {__version__}", root_is_purelib=root_is_purelib
    ) as wheel:
        project_path = Path(project_name)
        # step 1: create dist-info dir, write metadata into it.
        # TODO: Move into prepare_metadata
        wheel.write_metadata(metadata)

        srcdir = Path.cwd() / "src"
        pth_filename = f"_{project_name}.pth"
        wheel.write_file(pth_filename, str(srcdir))

        for file in build_dir.iterdir():
            # TODO: Refine this based on the expected kinds of build artifacts,
            # optimally from settings.
            if file.suffix == ".so":
                wheel.write_file(
                    project_path / file.name, build_dir / file, timestamp=datetime.now()
                )

    return wheel_file.name


def get_requires_for_build_editable(
    config_settings: dict[str, str] | None = None,
) -> list[str]:
    return []


def prepare_metadata_for_build_editable(
    metadata_directory: str | os.PathLike[str],
    config_settings: dict[str, str] | None = None,
) -> None:
    prepare_metadata_for_build_wheel(
        metadata_directory=metadata_directory, config_settings=config_settings
    )
