[build-system]
requires = ["hanzo", "nanobind"]
build-backend = "hanzo"

[project]
name = "hello-cc"
version = "0.1.0"
keywords = ["hello", "c++"]
requires-python = ">=3.10"


[tool.uv.sources]
hanzo = { path = "../../..", editable = true }

[tool.hanzo]
stable-abi = ">=3.12"

[tool.hanzo.targets.nanobind]
type = "cc-library"
rootpath = "@python.site/nanobind"
sources = [
    { include = ["src/*.cpp", "src/*.h"], exclude = ["src/nb_combined.cpp"] }
]
headers = ["include", "@python.include"]
includes = [ "include", "ext/robin_map/include", "@python.include"]
flags = [
    "-std=c++17",  # TODO: Set standard in hanzo top-level C++ settings
    "-fPIC",
    "-fvisibility=hidden",
    "-fno-strict-aliasing",
]
linkflags = [
    "-bundle",
    "-Wl,-headerpad_max_install_names",
    "-Wl,@@rootpath/cmake/darwin-ld-cpython.sym",
    "-Wl,-x",
    "-Wl,-S",
    "-Wl,-dead_strip",
]

[tool.hanzo.targets.hello_ext]
type = "cc-extension"
sources = ["src/hello_ext.cc"]
dependencies = ["nanobind"]
